# Лабораторная работа 1. Работа с матрицами

## Часть 1. Библиотеки

В этой лабораторной работе вам понадобятся три библиотеки:

- `numpy` - основная библиотека для работы с матрицами;
- `scipy`, а точнее модуль `scipy.linalg`, содержащий множество функций линейной алгебры.

Подключить их можно следующим образом:

In [1]:
# Запустите этот код
import numpy as np
import scipy.linalg as sla

Теперь вы можете вызвать, например, функцию `scipy.linalg.det()` с помощью кода `sla.det()`, а функцию `numpy.exp()` - с помощью кода `np.exp()`.

**Основные объекты и операции линейной алгебры в NumPy и SciPy**

Основной объект, с которым вам придётся работать в этой и в следующих лабораторных - это матрицы. В библиотеке `numpy` они представлены классом `numpy.ndarray`. Матрицу можно создать из двумерного (а на самом деле и не только двумерного) массива следующим образом:

In [ ]:
# Запустите этот код
A = np.array([[1, 2, 3], [4, 5, 6]])

print(A)
print(A.shape) # пара (число строк, число столбцов)

[[1 2 3]
 [4 5 6]]
(2, 3)


Обратите внимание, что матрица заполняется *по строкам*.

Есть и много других конструкторов матриц. Например, единичная матрица размера $n\times n$ создаётся с помощью функции `numpy.eye(n)`. Со всем многообразием конструкторов можно ознакомиться [на этой странице](https://numpy.org/doc/stable/reference/routines.array-creation.html).

Зачастую бывает нужно получить доступ к подматрицам данной матрицы, и `numpy` предоставляет множество удобных средств, как это сделать (такая операция называется *slicing*):
- элемент с номером `(i,j)`: `A[i,j]`
- i-я строка матрицы: `A[i,:]`
- j-й столбец матрицы: `A[:,j]`

**Внимание!** Оба варианта, и `A[i,:]`, и `A[:,j]`, дают не строку или столбец, а одномерный вектор. Если вы хотите получить вектор-строку или вектор-столбец соответственно, используйте вот такой синтаксис: `A[i:i+1,:]`, и `A[:,j:j+1]`
- строки с нулевой по i-ю: `A[:i+1,:]`
- столбцы с j-го по последний: `A[:,j:]`
- строки с i-й по k-ю: `A[i:k,:]`

В некоторых случаях нужно получить доступ к (прямоугольной) подматрице, элементы которой находятся на пересечении строк из списка `rows` и столбцов `columns`. В этом случае `A[rows, columns]` даст не то, что вы ожидаете (можете попробовать это сделать сами и увидеть, что получится; только возьмите `rows` и `columns` одного размера). Справиться с этой задачей позволяет выражение `A[np.ix_(rows, columns)]`.

*Умножение матриц* производится с помощью оператора `np.dot()`. Есть два варианта написания: `A.dot(B)` и `np.dot(A, B)`.

Обычные знаки арифметических действий (`+`, `-`, `*`) зарезервированы для поэлементных операций. Например, `A * B` - это матрица, элементами которой являются произведения $A_{ij}B_{ij}$. Помимо этих есть и множество других поэлементных операций. Например, `numpy.exp(A)` - это матрица, элементами которой являются экспоненты элементов матрицы `A`.

Чтобы получить матрицу, *транспонированную* к матрице `A`, напишите просто `A.T`. 

В некоторых случаях бывает нужно создавать *случайные матрицы*: например, при проведении экспериментов или для инициализации итеративных методов. Средства для этого предоставляет пакет [numpy.random](https://numpy.org/doc/stable/reference/random/index.html). Так, `np.random.rand(m,n)` - это матрица $m\times n$, элементы которой независимо выбраны из равномерного распределения на интервале `[0;1)`. 

Для *решения систем линейных уравнений* в пакете `scipy.linalg` есть множество методов, рассмотрение которых выходит за пределы курса линейной алгебры. Мы предлагаем пользоваться функцией `scipy.linalg.solve`, основанной на методе Гаусса. Отметим, что `scipy.linalg.solve(A, B)` выдаёт решение уравнения $AX = B$ (или ошибку), где $B$ может быть как вектором, так и матрицей.

Найти обратную матрицу для матрицы $A$ можно с помощью функции `sla.inv(A)`.

**Копирование сложных объектов в Python**

Когда вы делаете присваивание каких-то сложных объектов, как правило оно происходит по ссылке. Например, код
```
B = A
B[0,0] = 10
```
приведёт к изменению матрицы `A`.

Не попадайтесь в эту ловушку! Если вы хотите работать с копией как с независимой матрицей, используйте метод `copy()`:
```
B = A.copy()
```

**Где искать помощь**

Библиотеки `numpy` и `scipy` снабжены прекрасной документацией. Если у вас возникают вопросы о том, как работает та или иная функция (или даже как называется функция, выполняющая то, что вам нужно), вы почти всегда можете найти там ответы.

[Ссылка на документацию пакета scipy.linalg](https://docs.scipy.org/doc/scipy/reference/linalg.html)

**Задание 1**

В качестве первого задания найдите соответствующие функции в библиотеке и сделайте следующее:

- создайте нулевую матрицу $Z$ размера $3\times4$;

- создайте диагональную матрицу $5\times5$ с диагональными элементами 1, 2, 3, 4 и 5;

- найдите её след;

- найдите обратную к ней матрицу;

- сгенерируйте случайную матрицу $X$ размера $4\times5$;

- найдите определитель подматрицы матрицы $X$, расположенной на пересечении 2 и 3 строки и 1 и 2 столбца; считаем, что строки и столбцы нумеруются с единицы (используйте slicing!). Такой определитель называется *минором* матрицы $X$;

- найдите произведение $X^TX$.

Пожалуйста, каждый пункт делайте в новом блоке и не забывайте выводить результаты.

In [1]:
import numpy as np
import scipy.linalg as sla
# создайте нулевую матрицу Z размера 3×4;
Z = np.zeros((3,4))
print(Z, Z.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] (3, 4)


In [7]:
# создайте диагональную матрицу 5×5 с диагональными элементами 1, 2, 3, 4 и 5;
Z = np.diag(np.arange(1, 6))
print(Z)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [8]:
# найдите её след
diag_sum = np.trace(Z)
print(diag_sum)

15


In [9]:
# найдите обратную к ней матрицу;
res = sla.inv(Z)
print(res)
# чтобы проверить умножим Z на обратную
# check = np.matmul(Z, res)
# print(check)

[[ 1.          0.         -0.          0.         -0.        ]
 [ 0.          0.5        -0.          0.         -0.        ]
 [ 0.          0.          0.33333333  0.         -0.        ]
 [ 0.          0.          0.          0.25       -0.        ]
 [ 0.          0.          0.          0.          0.2       ]]


In [117]:
# сгенерируйте случайную матрицу X размера 4×5;
X = np.random.rand(4,5)
X = np.random.randint(1, 6, (4, 5))
print(X)

[[1 4 3 4 5]
 [3 4 4 2 5]
 [1 2 2 1 4]
 [2 5 3 5 3]]


In [53]:
# найдите определитель подматрицы матрицы X, расположенной на пересечении 2 и 3 строки и 1 и 2 столбца; считаем, что строки и столбцы нумеруются с единицы (используйте slicing!). 
# Такой определитель называется минором матрицы X;
X_det = X.copy()
X_det = X_det[np.ix_([1,2],[0,1])]
print(X_det)
det = np.linalg.det(X_det) 
print(det)
print(np.linalg.det(X_det.T))


[[3 3]
 [4 2]]
-6.0
-6.0


In [118]:
# найдите произведение XT X.
print(X, "\n\n", X.T)
res = np.dot(X.T,X)
print(res)
print()

[[1 4 3 4 5]
 [3 4 4 2 5]
 [1 2 2 1 4]
 [2 5 3 5 3]] 

 [[1 3 1 2]
 [4 4 2 5]
 [3 4 2 3]
 [4 2 1 5]
 [5 5 4 3]]
[[15 28 23 21 30]
 [28 61 47 51 63]
 [23 47 38 37 52]
 [21 51 37 46 49]
 [30 63 52 49 75]]



## Часть 2. Матричные вычисления

Использование циклов в Python лучше по возможности избегать и важно уметь находить способы делать всё библиотечными средствами.

В качестве примера рассмотрим две задачи:

**1.** Предположим, нужно вычислить суммы элементов в каждой строке матрицы `A`. Ясно, что можно написать простую функцию с двумя циклами, которая это посчитает, но так лучше не делать. Правильный способ такой:
```
A.sum(axis=1)
```
Параметр `axis=1` означает, что суммы берутся по строкам. Если вы хотите просуммировать по столбцам, укажите `axis=0`. Если вообще пропустить параметр `axis` (вызвать `A.sum()`), то функция вернёт сумму *всех* элементов матрицы.

**2.** Теперь допустим, что нам нужно каждый столбец матрицы `A` нужно умножить на некоторое число. Более точно, пусть у нас есть (одномерный) вектор `w = np.array([w_1,...,w_n])`, и мы должны `i`-й столбец `A` умножить на число `w_i`. Опять же, это можно сделать в пару циклов, но лучше использовать операцию поэлементного умножения:
```
A * w.reshape((1,n))
```
Оператор `reshape` нужен для того, чтобы из одномерного вектора сделать вектор-строку.

Аналогично если на числа `w_1,...,w_n` умножаются *строки* матрицы, нужно превратить `w` в вектор-столбец:
```
A * w.reshape((n,1))
```

Дальше вам будет предложено попрактиковаться в матричных вычислениях. В следующих трёх заданиях нельзя пользоваться циклами; вместо этого постарайтесь свести всё к библиотечным функциям. Чтобы убедиться, что получилось именно то, что нужно, пишите собственные тесты со случайными матрицами.

**Задание 2** Напишите функцию `prod_and_sq_sum(A)`, вычисляющую произведение и сумму квадратов диагональных элементов квадратной матрицы `A`.

In [59]:
def prod_and_sq_sum(A):
  diag = np.diag(A)
  prod = np.prod(diag)
  sq = np.square(diag)
  print (diag,"prod:", prod, "sq:", sq, "sum(sq):", sum(sq))

In [66]:
# проверка
A = np.random.randint(1, 6, (4, 4))
print(A)
prod_and_sq_sum(A)
A = np.ones((4,4))
print(A)
prod_and_sq_sum(A)

[[3 1 3 4]
 [1 4 2 1]
 [2 4 5 1]
 [3 4 4 4]]
[3 4 5 4] prod: 240 sq: [ 9 16 25 16] sum(sq): 66
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[1 1 1 1] prod: 1 sq: [1 1 1 1] sum(sq): 4


**Задание 3** Для матриц `A` и `B` размера $n\times m$ обозначим через $a_1,\ldots,a_m$ и $b_1,\ldots,b_m$ соответственно их столбцы. Напишите функцию `f(A, B, k)`, вычисляющую

$$\sum_{i=1}^{\min(k,m)}a_i^Tb_i$$

In [52]:
def f(A, B, k):
  # каждый столбец а транспонировать и умножить на каждый столбец матрицы б, суммировать
  #print("at", AT[:, :k], "a", A[:k, :].T, "b", B[:k, :])
  print(A.reshape((-1,k)))
  A = A[:, :k].T 
  B = B[:, :k]
  # sum = AT[:, :k] * B[:, :k]
  print("A\n", A, "\nB\n", B)
  prod = A * B
  print("prod\n", prod, "\nsum\n", np.sum(prod, axis = 0))

In [53]:
# проверка
import numpy as np
import scipy.linalg as sla
n = np.random.randint(2, 5)
m = np.random.randint(4, 5)
k = np.random.randint(2, 4)
print(k)

A = np.random.randint(1, 6, (n, m))
B = np.random.randint(1, 6, (n, m))
k = min(k,m)
print("A\n", A, "\nB\n", B)
f(A, B, k)

3
A
 [[1 4 4 3]
 [2 2 2 1]
 [5 4 4 1]] 
B
 [[3 3 1 2]
 [2 2 2 1]
 [5 5 4 2]]
[[1 4 4]
 [3 2 2]
 [2 1 5]
 [4 4 1]]
A
 [[1 2 5]
 [4 2 4]
 [4 2 4]] 
B
 [[3 3 1]
 [2 2 2]
 [5 5 4]]
prod
 [[ 3  6  5]
 [ 8  4  8]
 [20 10 16]] 
sum
 [31 20 29]


**Задание 4** Напишите функцию `get_diag(A,B)`, принимающую две матрицы `A` и `B` и возвращающую вектор диагональных элементов произведения `AB`, не вычисляя произведение целиком. 

In [91]:
def get_diag(A, B):
  diagA = np.diag(A)
  diagB = np.diag(B)
  prod = diagA * diagB
  print("A", diagA, "B", diagB, "\nprod", prod)

In [97]:
# проверка
A = np.random.randint(1, 6, (4, 4))
B = np.random.randint(1, 6, (4, 4))
print(A,"\n\n", B)
get_diag(A, B)
C = np.ones((4,4))
D = np.full((4,4), 2)
get_diag(C, D)

[[4 4 3 5]
 [1 1 5 4]
 [3 2 4 3]
 [5 2 5 2]] 

 [[2 5 2 4]
 [3 5 3 1]
 [3 4 4 5]
 [5 2 2 3]]
A [4 1 4 2] B [2 5 4 3] 
prod [ 8  5 16  6]
A [1. 1. 1. 1.] B [2 2 2 2] 
prod [2. 2. 2. 2.]
