# Лабораторная работа 6. Выбор оптимального классификатора

В этой лабораторной работе вам потребуется выбрать наилучший классификатор с оптимальными параметрами для задачи про пассажиров ["Титаника"](https://ru.wikipedia.org/wiki/Титаник).

__Задание 1.__  
Загрузите данные (см. предыдущую лабораторную работу).

In [24]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

train = pd.read_csv("train.csv") # lab5_input
test = pd.read_csv("test.csv") # lab5_input

__Задание 2.__  
Проведите предобработку данных (см. предыдущую лабораторную работу).

In [25]:
def process_age(df, cut_points, label_names):
    df['Age'] = df['Age'].replace(np.NaN, -0.5) #fillna
    df['Age_categories'] = pd.cut(df['Age'], bins=cut_points, labels=label_names)
    return df

cut_points = [-1, 0, 5, 12, 18, 35, 60, 100]
label_names = ["Missing", "Infant", "Child", "Teenager", "Young_Adult", "Adult", "Senior"]
train = process_age(train, cut_points, label_names)
test = process_age(test, cut_points, label_names)

In [26]:
def create_dummies(df, column_name):
    dum = pd.get_dummies(df[column_name], prefix=[column_name])
    df = pd.concat([df,dum],axis=1)
    return df

train = create_dummies(train, "Pclass")
test = create_dummies(test, "Pclass")

train = create_dummies(train, "Sex")
test = create_dummies(test, "Sex")

train = create_dummies(train, "Age_categories")
test = create_dummies(test, "Age_categories")

#train = create_dummies(train, "Embarked")
#test = create_dummies(test, "Embarked")

__Задание 3.__  
Примените масштабирование признаков (`StandardScaler`, `MinMaxScaler`).

In [27]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
drop_cols = ['Name', 'Sex', 'PassengerId', 'Age', 'Age_categories', 'Ticket', 'Cabin', 'Embarked', 'Pclass']
drop_cols = ['PassengerId', 'Pclass', 'Name', 'Sex', 'Age',
                 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'Age_categories'] 
train = train.drop(columns=drop_cols, axis=1)
test = test.drop(columns=drop_cols, axis=1)
#print(train[train.isnull().any(axis=1)])

#features = ['Parch', 'SibSp', 'Fare']
#train[features]= MinMaxScaler().fit_transform(train[features])
#test[features]= MinMaxScaler().fit_transform(test[features])

__Задание 4.__  
Примените различные преобразования признаков (`PolynomialFeatures`).

In [28]:
from sklearn.preprocessing import PolynomialFeatures

tpoly = PolynomialFeatures(degree=3, interaction_only=True)
tpoly3 = tpoly.fit_transform(train)
print(tpoly3)

fpoly = PolynomialFeatures(degree=3, interaction_only=False)
fpoly3 = fpoly.fit_transform(train)
print(fpoly3)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]
[[1. 0. 0. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


__Задание 5.__  
Обучите несколько классификаторов, в том числе:  
1. Логистическую регрессию (`LogisticRegression`).
1. Метод опорных векторов (`SVC`).
1. Метод *k* ближайших соседей (`KNeighborsClassifier`).
1. Наивный байесовский классификатор (`MultinomialNB`).
1. Деревья решений (`DecisionTreeClassifier`).
1. Случайный лес (`RandomForestClassifier`).
1. AdaBoost (`AdaBoost`).
1. Градиентный бустинг (`GradientBoostingClassifier`).

Для обучения и проверки качества можно использовать функцию `train_test_split()`.

In [29]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier

from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [30]:
y = train['Survived']
df = train.copy()
df = df.drop(['Survived'], axis=1)

x_train, x_test, y_train, y_test = train_test_split(df, y, train_size=0.8, random_state=42)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape) 

(712, 12) (179, 12) (712,) (179,)


In [31]:
# Логистическая регрессия
lr = LogisticRegression(random_state=42)
lr.fit(x_train, y_train) 
y_pred = lr.predict(x_test)
print(lr.score(x_test, y_test))

0.8044692737430168


In [32]:
# Метод опорных векторов (SVC)
svc = SVC(random_state=42)
svc.fit(x_train, y_train)
print(svc.score(x_test, y_test))

0.8156424581005587


In [33]:
# Метод k ближайших соседей (KNeighborsClassifier)
knn = KNeighborsClassifier()
knn.fit(x_train, y_train)
print(knn.score(x_test, y_test))

0.8100558659217877


In [34]:
# Наивный байесовский классификатор (MultinomialNB)
gaussian = MultinomialNB()
gaussian.fit(x_train, y_train)
print(gaussian.score(x_test, y_test))

0.770949720670391


In [35]:
# Деревья решений (DecisionTreeClassifier)
decision_tree = DecisionTreeClassifier(random_state=42)
decision_tree.fit(x_train, y_train)
print(decision_tree.score(x_test, y_test))

0.8044692737430168


In [36]:
# Случайный лес (RandomForestClassifier)
random_forest = RandomForestClassifier(random_state=42)
random_forest.fit(x_train, y_train)
print(random_forest.score(x_test, y_test))

0.8044692737430168


In [37]:
# AdaBoost (AdaBoost)
ada = AdaBoostClassifier(random_state=42)
ada.fit(x_train, y_train)
print(ada.score(x_test, y_test))

0.8044692737430168


In [38]:
# Градиентный бустинг (GradientBoostingClassifier)
gbc = GradientBoostingClassifier(random_state=42).fit(x_train, y_train)
print(gbc.score(x_test, y_test))

0.8100558659217877


__Задание 6.__  
При помощи `Pipeline` и `GridSearchCV` выберите оптимальную архитектуру:
1. Метод масштабирования.
1. Степень полинома в `PolynomialFeatures`.
1. Параметры классификаторов (в том числе, параметры регуляризации).

Заносите в таблицу Excel результаты тестирования (варианты параметров, оценки качества).

In [ ]:
import sklearn.model_selection as model_selection

classifiers = [
    LogisticRegression(),
    SVC(),
    KNeighborsClassifier(),
    MultinomialNB(),
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    AdaBoostClassifier(),
    GradientBoostingClassifier()
    ]

poly_list = [
             PolynomialFeatures(degree=2, include_bias=True, interaction_only=False),
             PolynomialFeatures(degree=2, include_bias=False, interaction_only=False),
             PolynomialFeatures(degree=2, include_bias=False, interaction_only=True),
             PolynomialFeatures(degree=2, include_bias=True, interaction_only=True),
             PolynomialFeatures(degree=3, include_bias=True, interaction_only=False),
             PolynomialFeatures(degree=3, include_bias=False, interaction_only=False),
             PolynomialFeatures(degree=3, include_bias=False, interaction_only=True),
             PolynomialFeatures(degree=3, include_bias=True, interaction_only=True),
             PolynomialFeatures(degree=4, include_bias=True, interaction_only=False),
             PolynomialFeatures(degree=4, include_bias=False, interaction_only=False),
             PolynomialFeatures(degree=4, include_bias=False, interaction_only=True),
             PolynomialFeatures(degree=4, include_bias=True, interaction_only=True)
]
# LogisticRegression()
params1 = {"poly__degree": range(1,4,1), "clf__solver": ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'], 
           "clf__max_iter": range(700,1000,100)} # range start stop step
# SVC
params2 = {"poly__degree": range(1,4,1),"clf__kernel":["rbf", "poly", "linear", "sigmoid"], "clf__gamma": ["auto", "scale"], "clf__degree":range(1,6,1)}
# KNeighborsClassifier()
params3 = {"poly__degree": range(1,4,1),"clf__n_neighbors": range(5,10,2), "clf__weights": ["uniform", "distance"],
         "clf__algorithm": ['ball_tree', 'kd_tree']}
# MultinomialNB()
params4 = {"poly__degree": range(1,4,1),"clf__fit_prior": ['True', 'False'], "clf__alpha": [0.5,0.3,0.1]}
# DecisionTreeClassifier()
params5 = {"poly__degree": range(1,4,1),"clf__criterion":["gini", "entropy"], "clf__max_depth": range(2,30,3), "clf__min_samples_split": [2,3],
           "clf__min_samples_leaf": range(1,10,3)}   
# RandomForestClassifier()
params6 = {"poly__degree": range(1,4,1),"clf__criterion":["gini", "entropy"], "clf__class_weight":["balanced", "balanced_subsample"], 
           "clf__max_depth": range(4,10,2), "clf__min_samples_leaf": [1,2,5], "clf__n_estimators":range(50,150,50)} 
# AdaBoostClassifier()
params7 = {"poly__degree": range(1,5,1),"clf__learning_rate":np.arange(0.3,0.7,0.1), "clf__n_estimators":range(20,60,20),
         "clf__algorithm":["SAMME", "SAMME.R"]} 
# GradientBoostingClassifier()
params8 = {"poly__degree": range(1,5,1),"clf__loss":["deviance", "exponential"], 
           "clf__learning_rate":[0.065,0.07,0.075], "clf__n_estimators":range(40,100,20),
           "clf__min_samples_leaf": range(1,4,1), "clf__max_depth": range(1,4,1), 
           "clf__max_features": ["auto", "sqrt", "log2"], "clf__validation_fraction":np.arange(0.01,0.5,0.1)}


parameters = [params1, params2, params3, params4, params5, params6, params7, params8]
i = 0
for classifier in classifiers:
    print(classifier)
    pipe = Pipeline(steps=[('scaler', MinMaxScaler()), #MinMaxScaler() StandardScaler()
                            ('poly', PolynomialFeatures()),
                            ('clf', classifier) # , return_train_score = True
                      ])
    grid_cv = model_selection.GridSearchCV(pipe, parameters[i], scoring='accuracy')
    grid_cv.fit(x_train, y_train)
    print("model best score: ", grid_cv.best_score_)    
    print(grid_cv.best_params_)
    model = grid_cv.best_estimator_
    print("model test score: ", model.score(x_test, y_test))
    i+=1

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
model best score:  0.8033389146065202
{'clf__max_iter': 700, 'clf__solver': 'newton-cg', 'poly__degree': 1}
model test score:  0.8044692737430168
SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
model best score:  0.8075150201910765
{'clf__degree': 1, 'clf__gamma': 'scale', 'clf__kernel': 'sigmoid', 'poly__degree': 3}
model test score:  0.776536312849162
KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_

Выходные данные были обрезаны до нескольких последних строк (5000).
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Invalid value for max_features: 'None'. Allowed string values are 'auto', 'sqrt' or 'log2'.

  FitFailedWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Invalid value for max_features: 'None'. Allowed string values are 'auto', 'sqrt' or 'log2'.

  FitFailedWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Invalid value for max_features:

__Задание 7.__  
1. Выберите несколько лучших классификаторов (от 3 до 10).
1. Обучите выбранные классификаторы на всех доступных размеченных данных.
1. Получите результаты предсказания для тестовых данных.
1. Отправьте результаты на сервер [Kaggle](https://ru.wikipedia.org/wiki/Титаник).

In [ ]:
# Ваш код здесь
x_train